### PR TITLE
Fix issues with the Notice of Departure feature

### LINKED ISSUE #11: Invalid date causes uncaught error
**Describe the bug**
When entering an invalid date in the Notice of Departure Form, the bot is stuck on thinking and throws an error in the output.

**To Reproduce**
1. Click "File Notice of Departure" button on the template
2. Enter anything but a valid date (eg. just the number 1)
3. Click submit

**Expected behavior**
An error message to show.

**Screenshots**

**Desktop:**
 - OS: Ubuntu 20.04
- Installation: Source

**Additional context**
[snippet.log](https://github.com/user-attachments/files/20266417/snippet.log)

### PR DESCRIPTION
**Pull request by Bill3621**
1. Actually fix #11, the previous fix didn't use the correct formatter
2. Fixes some `interaction has already been acknowledged` errors
3. Added a check to not allow dates in the past
4. Fixes template of notice of departure not replacing placeholders like &filler&

### CODE REVIEW

File: src/main/kotlin/dev/vxrp/bot/events/modals/NoticeOfDepartureModals.kt [hunk 1]
```diff
@@ -32,7 +42,7 @@ class NoticeOfDepartureModals(val event: ModalInteractionEvent, val config: Conf
                 description = ColorTool().useCustomColorCodes(translation.noticeOfDeparture.embedDecisionSentBody)
             }
 
-            event.reply_("", listOf(embed)).setEphemeral(true).queue()
+            event.hook.send("", listOf(embed)).setEphemeral(true).queue()
```
Comment (Vxrpenter) [inline src/main/kotlin/dev/vxrp/bot/events/modals/NoticeOfDepartureModals.kt:45]: Why did you change it to use `hook.send()` without deferring the replies? It's also not an interaction that needs deferring, cause it's a rather short interaction.

File: src/main/kotlin/dev/vxrp/bot/events/modals/NoticeOfDepartureModals.kt [hunk 2]
```diff
@@ -2,25 +2,35 @@ package dev.vxrp.bot.events.modals
...
             } catch (_: DateTimeParseException) {
-                event.reply_("Please enter a valid date format to proceed").queue()
+                event.hook.send("Please enter a valid date format to proceed").queue()
+                return
+            }
+
+            val currentDate = LocalDate.now()
+            val parsedDate = LocalDate.parse(date, formatter)
+            if (parsedDate.isBefore(currentDate)) {
+                event.hook.send("Please enter a date in the future to proceed").queue()
```
Comment (Vxrpenter) [inline src/main/kotlin/dev/vxrp/bot/events/modals/NoticeOfDepartureModals.kt:33]: Why did you change it to use `hook.send()` without deferring the replies? It's also not an interaction that needs deferring, cause it's a rather short interaction.

File: src/main/kotlin/dev/vxrp/bot/events/modals/NoticeOfDepartureModals.kt [hunk 3]
```diff
@@ -2,25 +2,35 @@ package dev.vxrp.bot.events.modals
...
             val date = event.values[0].asString
             val reason = event.values[1].asString
+            val formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy")
 
             try {
-                LocalDate.parse(date)
+                LocalDate.parse(date, formatter)
             } catch (_: DateTimeParseException) {
-                event.reply_("Please enter a valid date format to proceed").queue()
+                event.hook.send("Please enter a valid date format to proceed").queue()
```
Comment (Vxrpenter) [inline src/main/kotlin/dev/vxrp/bot/events/modals/NoticeOfDepartureModals.kt:26]: Why did you change it to use `hook.send()` without deferring the replies? It's also not an interaction that needs deferring, cause it's a rather short interaction.

File: src/main/kotlin/dev/vxrp/bot/events/modals/NoticeOfDepartureModals.kt [hunk 4]
```diff
@@ -2,25 +2,35 @@ package dev.vxrp.bot.events.modals
...
+                return
+            }
+
+            val currentDate = LocalDate.now()
```
Comment (Vxrpenter) [inline src/main/kotlin/dev/vxrp/bot/events/modals/NoticeOfDepartureModals.kt:30]: Why don't you parse this date with the formatter, but you parse the other one?

File: src/main/kotlin/dev/vxrp/bot/events/modals/NoticeOfDepartureModals.kt [hunk 5]
```diff
@@ -2,25 +2,35 @@ package dev.vxrp.bot.events.modals
...
 import java.time.LocalDate
+import java.time.format.DateTimeFormatter
 import java.time.format.DateTimeParseException
 
 class NoticeOfDepartureModals(val event: ModalInteractionEvent, val config: Config, val translation: Translation) {
     suspend fun init() {
         if (event.modalId.startsWith("notice_of_departure_general")) {
             val date = event.values[0].asString
             val reason = event.values[1].asString
+            val formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy")
```
Comment (Vxrpenter) [inline src/main/kotlin/dev/vxrp/bot/events/modals/NoticeOfDepartureModals.kt:21]: Is formatting the date required? It should be formatted by parsing it through `LocalDate.parse()` by default, to a format like this `yyyy-MM-dd`. It's easier to only format it once it will be shown to users.

**Review by Vxrpenter — CHANGES_REQUESTED** [review]
Could you look at some of the changes I suggested?

File: src/main/kotlin/dev/vxrp/bot/events/modals/NoticeOfDepartureModals.kt (hunk 5 above)
Comment (Bill3621) [reply src/main/kotlin/dev/vxrp/bot/events/modals/NoticeOfDepartureModals.kt:21]: The user input should be in the format of `dd.MM.yyyy` like the modal tells the user, but using `LocalDate.parse()` without the formatter causes this format to not work, even though the modal asks the user for this format.

Entering `20.05.2025` without the formatter:
Discord_qkgg1x2u9B

With the formatter:
Discord_F4lWn8NbaF

File: src/main/kotlin/dev/vxrp/bot/events/modals/NoticeOfDepartureModals.kt (hunk 1 above)
Comment (Bill3621) [reply src/main/kotlin/dev/vxrp/bot/events/modals/NoticeOfDepartureModals.kt:45]: I am actually not sure why `hook.send()` is required here (and in the other cases too) but when I tried using `reply_`, the following error occured:
`java.lang.IllegalStateException: This interaction has already been acknowledged or replied to. You can only reply or acknowledge an interaction once!`

File: src/main/kotlin/dev/vxrp/bot/events/modals/NoticeOfDepartureModals.kt (hunk 5 above)
Comment (Vxrpenter) [reply src/main/kotlin/dev/vxrp/bot/events/modals/NoticeOfDepartureModals.kt:21]: Makes sense

File: src/main/kotlin/dev/vxrp/bot/events/modals/NoticeOfDepartureModals.kt (hunk 1 above)
Comment (Vxrpenter) [reply src/main/kotlin/dev/vxrp/bot/events/modals/NoticeOfDepartureModals.kt:45]: That either happens when there are 2 instances of the same bot running, or two replys are send for the same interaction

File: src/main/kotlin/dev/vxrp/bot/events/modals/NoticeOfDepartureModals.kt (hunk 4 above)
Comment (Bill3621) [reply src/main/kotlin/dev/vxrp/bot/events/modals/NoticeOfDepartureModals.kt:30]: `LocalDate.now()` returns a `LocalDate` object directly, so there's no need to parse or format it. The formatter is only required for converting a user-provided string into a `LocalDate`, which is why it's used with `LocalDate.parse(...)` but not with `LocalDate.now()`.

File: src/main/kotlin/dev/vxrp/bot/events/modals/NoticeOfDepartureModals.kt (hunk 1 above)
Comment (Bill3621) [reply src/main/kotlin/dev/vxrp/bot/events/modals/NoticeOfDepartureModals.kt:45]: I don't see a part where it should send two replies and it's only running once (I verified this by closing the bot process and testing if it would still reply, which it didn't)

Comment (Vxrpenter) [reply src/main/kotlin/dev/vxrp/bot/events/modals/NoticeOfDepartureModals.kt:45]: Then we can leave it as is. I just tested it on my own machine and it throws the same error

Comment (Bill3621) [reply src/main/kotlin/dev/vxrp/bot/events/modals/NoticeOfDepartureModals.kt:45]: I think I've actually figured out the issue. The previous fix for #8 actually defers the reply for ALL modal interactions, not just for the ticket creation.

**Comment by Bill3621** [comment]
This reverted the change to use `hook.send()` and fixed the ticket creation interaction deferring all modal interactions.

**Review by Vxrpenter — APPROVED** [review]
Oh, didn't even see that back there (professional maintainer xD)
